import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import woman from "../../public/assets/main_banner_woman.svg"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/assets/main_banner_woman.svg" alt="m1" />
        <img src={woman} alt="m1" />
        <Image
          src={woman}
          priority={true}
          unoptimized
        />
        <Image
          src={"/assets/main_banner_woman.svg"}
          priority={true}
          height={500}
          width={500}
          unoptimized
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
